### ISSUE TITLE
Go to v0.10.0

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#158]
We should release a new version of `CTBase.jl`. Before doing that, we can finalise some issues:

- [ ] https://github.com/control-toolbox/CTBase.jl/issues/155. No more `Index` type for the constraints.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/152. I think that this issue is ok. Do we close it?
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/151. We have to make a decision. Note that in `State`, one day there will be also the `Matrix` type. I like to keep these aliases since we need unions of types.
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/144. The new version can be done before this one is closed I guess.
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/142. The new version can be done before this one is closed I guess.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/137. Maybe we can add getters for `CTDirect`.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/128. We have to make a decision. We have decided to use `Requires.jl`. See https://github.com/control-toolbox/OptimalControl.jl/issues/179.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/124. Add some documentation. See https://github.com/control-toolbox/OptimalControl.jl/issues/155.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/122: bug, urgent!
- [x] https://github.com/control-toolbox/CTBase.jl/issues/114. We may check if it is better to use pre-allocation.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/101. @ocots should take a look.
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/71. There is some documentation to add and take a look at this one.
- [x] https://github.com/control-toolbox/CTBase.jl/issues/25. Do we close the issue?

**Comment by ocots** [comment]
@jbcaillau Pin.

**Comment by ocots** [comment]
Before doing the new release:

- fix bug: https://github.com/control-toolbox/CTBase.jl/issues/122

**Comment by PierreMartinon** [comment]
Ok, I think I'm done with updating CTDirect for CTBase 0.10. Release 0.7 should follow shortly :)
